# {OttoCODE repo}/src/version.pri

DEFINES += OCVER_MAJOR=5
DEFINES += OCVER_MINOR=23
DEFINES += OCVER_MICRO=1
DEFINES += OCVER_BRANCH=0
DEFINES += OCVER_STRING="v5.23A"
DEFINES += OC_VER_TRUNKNAME="develop"
DEFINES += OC_VER_BRANCHNAME="main"

VER_MAJ = 5
VER_MIN = 23
VER_PAT = 0
